---
- name: Create download directory
  ansible.windows.win_file:
    path: 'C:\opt\downloads'
    state: directory

- name: Download munin installer
  ansible.windows.win_get_url:
    url: "{{ munin_installer }}"
    dest: "C:\\opt\\downloads\\{{ munin_installer_basename }}"

- name: Info message
  ansible.builtin.debug:
    msg: "To fix: The windows munin client must be installed manually. Log into the server, go to C:/opt/downloads and run the installer."
