---
- name: Create download directory
  ansible.windows.win_file:
    path: 'C:\opt\downloads'
    state: directory

- name: Download munin installer
  ansible.windows.win_get_url:
    url: "{{ munin_installer }}"
    dest: "C:\\opt\\downloads\\{{ munin_installer_basename }}"

- name: Run munin installer
  ansible.windows.win_shell: |
    C:\\opt\\downloads\\{{ munin_installer_basename }} /SILENT 
  args:
    chdir: "C:\\opt\\downloads"
