---
# Variables ##########

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}-family.yml"

- name: Include Distribution version specific variables
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  ignore_errors: true

- name: set facts based on defaults
  set_fact:
    "{{ item[8:] }}": "{{ lookup('vars', item) }}"
  when:
    - item is match("^default_")
    - vars[item[8:]] is not defined
  with_items:
    "{{ vars | list }}"

##########

- name: include client
  include: client.yml
  when: run_munin_client is defined


- name: include server
  include: server.yml
  when: run_munin_server is defined
