---
- name: restart munin-node
  service: name=munin-node state=restarted

- name: restart apache
  service: name={{ munin_apache_service }} state=restarted

- name: restart nginx
  service: name=nginx state=restarted

# During testing, munin-node-configure had to be run twice. Investigate.
- name: Run munin-node-configure
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    sleep 1
    sudo -u munin /opt/local/sbin/munin-node-configure --suggest --shell | sudo sh
    sleep 1
    sudo -u munin /opt/local/sbin/munin-node-configure --suggest --shell | sudo sh
    sleep 1
    /opt/local/bin/port reload munin
    sleep 1

- name: Run munin-node-configure-freebsd
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    sleep 1
    /usr/local/sbin/munin-node-configure --shell | sh -x
    sleep 1
    /usr/local/sbin/munin-node-configure --shell | sh -x
    sleep 1
    /usr/local/etc/rc.d/munin-node stop || true
    sleep 1
    /usr/local/etc/rc.d/munin-node start || true
  failed_when: false

- name: restart munin-node-mac
  command: |
    /opt/local/bin/port reload munin
